trigger:
- main  # Define the branch to trigger on, e.g., 'main', 'master'

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate VM image

variables:
  TEST_RAIL_USERNAME: ''
  TEST_RAIL_PASSWORD: ''
  JIRA_USERNAME: ''
  JIRA_API_TOKEN: ''

stages:
- stage: Checkout
  jobs:
  - job: Checkout
    steps:
    - checkout: self
    - checkout: git://maxxmuthu/PetStore@main  # Replace with your actual GitHub repository URL

- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    steps:
    - task: UseJavaVersion@1
      inputs:
        versionSpec: '11'  # Specify the Java version to use, adjust as needed

    - script: |
        mvn clean compile
        mvn test -Dsurefire.suiteXmlFiles=testng.xml
      displayName: 'Build and Test'

    - task: PublishHTML@1
      inputs:
        htmlReportName: 'Extent Reports'
        reportDirectory: 'test-output'
        reportFiles: 'extent-report.html'
        failIfNoFiles: false
        publishMode: 'inline'

    - task: MavenAuthenticate@0
      inputs:
        artifactsFeeds: 'jira-credentials, testrail-credentials'  # Use the service connections

    - script: |
        echo "##vso[task.setvariable variable=JIRA_USERNAME;issecret=false;isOutput=true]$(JIRA_USERNAME)"
        echo "##vso[task.setvariable variable=JIRA_API_TOKEN;issecret=true;isOutput=true]$(JIRA_API_TOKEN)"
        echo "##vso[task.setvariable variable=TEST_RAIL_USERNAME;issecret=false;isOutput=true]$(TEST_RAIL_USERNAME)"
        echo "##vso[task.setvariable variable=TEST_RAIL_PASSWORD;issecret=true;isOutput=true]$(TEST_RAIL_PASSWORD)"
      displayName: 'Set pipeline variables'

- stage: Cleanup
  jobs:
  - job: Cleanup
    steps:
    - script: |
        cleanWs
      displayName: 'Clean up workspace'