trigger:
- main  # Define the branch to trigger on, e.g., 'main', 'master'

pool:
  vmImage: 'ubuntu-latest'  # Choose an appropriate VM image

variables:
  TEST_RAIL_USERNAME: ''
  TEST_RAIL_PASSWORD: ''
  JIRA_USERNAME: ''
  JIRA_API_TOKEN: ''
  java.version: '16'  # Define the Java version to use

stages:
- stage: BuildAndTest
  jobs:
  - job: BuildAndTest
    steps:
    - script: |
        sudo apt-get update
        sudo apt-get install -y openjdk-$(java.version)-jdk
        echo "Java version:"
        java -version
      displayName: 'Set up Java'

    - script: |
        mvn clean compile
        mvn test -Dsurefire.suiteXmlFiles=testng.xml
      displayName: 'Build and Test'

    - script: |
        echo "Setting up TestRail credentials"
        echo "##vso[task.setvariable variable=TEST_RAIL_USERNAME;issecret=false;isOutput=true]$(TEST_RAIL_USERNAME)"
        echo "##vso[task.setvariable variable=TEST_RAIL_PASSWORD;issecret=true;isOutput=true]$(TEST_RAIL_PASSWORD)"

        echo "Setting up JIRA credentials"
        echo "##vso[task.setvariable variable=JIRA_USERNAME;issecret=false;isOutput=true]$(JIRA_USERNAME)"
        echo "##vso[task.setvariable variable=JIRA_API_TOKEN;issecret=true;isOutput=true]$(JIRA_API_TOKEN)"
      displayName: 'Set pipeline variables'

    - task: PublishBuildArtifacts@1
      inputs:
        pathtoPublish: 'test-output'
        artifactName: 'Extent Reports'
        publishLocation: 'Container'

- stage: Cleanup
  jobs:
  - job: Cleanup
    steps:
    - script: |
        cleanWs
      displayName: 'Clean up workspace'